name: hermez_sdk
version: 1.0.0+1
homepage: https://hermez.io
description: Hermez Flutter SDK (https://hermez.io). This plugin provides a cross-platform (iOS, Android).

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  web3dart: ^2.1.3
  web_socket_channel: ^2.1.0
  provider: ^5.0.0
  bip39: ^1.0.6
  hex: ^0.2.0
  ffi: ^1.0.0
  shared_preferences: ^2.0.6
  # path_provider_windows: ^0.1.0
  # tweetnacl: ^0.3.2
  # sha3: ^0.1.1
  # flutter_liquidcore: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.hermez.hermez_sdk
        pluginClass: HermezPlugin
      ios:
        pluginClass: HermezPlugin
      # macos:
        # pluginClass: HermezPlugin
      # web:
        # pluginClass: HermezPlugin
        # fileName: hello_web.dart

assets:
  - ERC20ABI.json
  - HermezABI.json
  - WithdrawalDelayerABI.json
