name: hermez_sdk
version: 1.0.0+1
homepage: https://hermez.io
description: Hermez Flutter SDK (https://hermez.io). This plugin provides a cross-platform (iOS, Android).

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

analyzer:
  enable-experiment:
    - non-nullable

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3 #0.12.0 # Update to 0.13.3 - current version needed for web3dart 1.2.3
  web3dart: ^2.1.3 # ^1.2.3 # Update to 2.1.3 - problem with bitcoin_flutter
  web_socket_channel: ^2.1.0 # 1.1.0 # Update to 2.1.0 - depends on crypto 3.0.0 - common dependency with web3dart and bip39 (crypto 2.0.3)
  provider: ^5.0.0
  bip39: ^1.0.6 # 1.0.3 update to 1.0.6
  hex: ^0.2.0 # 0.1.2 Update to 0.2.0 - current version needed for bitcoin_flutter
  ffi: ^1.0.0
  shared_preferences: ^2.0.5 # ^0.5.12+4 # Update to ^2.0.5
  # path_provider_windows: ^0.1.0
  # tweetnacl: ^0.3.2
  # sha3: ^0.1.1
  # flutter_liquidcore: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  #ffigen:
    # output: 'generated_bindings.dart'
      # headers:
      # entry-points:
    # - 'example.h'



# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.hermez.hermez_sdk
        pluginClass: HermezPlugin
      ios:
        pluginClass: HermezPlugin
      # macos:
        # pluginClass: HermezPlugin
      # web:
        # pluginClass: HermezPlugin
        # fileName: hello_web.dart

assets:
  - ERC20ABI.json
  - HermezABI.json
  - WithdrawalDelayerABI.json
